version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: stackoverflow_clone_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackoverflow_clone_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: stackoverflow_clone_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  # Ollama Model Downloader
  ollama-setup:
    image: ollama/ollama:latest
    container_name: stackoverflow_clone_ollama_setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Ollama server..."
        sleep 5
        echo "Pulling llama2 model..."
        ollama pull llama2
        echo "Model pull complete!"
    environment:
      - OLLAMA_HOST=ollama:11434
    restart: "no"

volumes:
  postgres_data:
    name: stackoverflow_clone_postgres_data
  ollama_data:
    name: stackoverflow_clone_ollama_data